version: "2.4"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.26
    ports:
      - "16686:16686"
      - "6831:6831/udp"
  scws:
    depends_on:
      - jaeger
    image: scws:all
    environment:
      JAEGER_AGENT_HOST: "jaeger"
      JAEGER_AGENT_PORT: 6831
      # JAEGER_SAMPLING_ENDPOINT: http://jaeger:5778/sampling
      JAEGER_TAGS: "service=frontend"
      JAEGER_SERVICE_NAME: "scws"
      #JAEGER_REPORTER_LOG_SPANS: true
      SCWS_INDEX_HTML: "calculator/index.html"
      SCWS_S3_BUCKET: "${AWS_BUCKET}"
      SCWS_S3_PREFIX: "/"
      SCWS_S3_AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      SCWS_S3_AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      SCWS_S3_AWS_REGION: "eu-west-1"
      SCWS_STORAGE: "s3"
      SCWS_VAULT_ADDRESS: "http://192.168.2.5:8200"
      SCWS_VAULT_TOKEN: "myroot"
      SCWS_VAULT_PATHS: "secret/data/test1"
    ports:
      - "8080:8080"
