version: "2.4"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.26
    # environment:
    #   - COLLECTOR_ZIPKIN_HOST_PORT="9411"
    # ports:
    #   - "5775:5775/udp"
    #   - "6831:6831/udp"
    #   - "6832:6832/udp"
    #   - "5778:5778"
    #   - "16686:16686"
    #   - "14268:14268"
    #   - "14250:14250"
    #   - "9411:9411"
    ports:
      - "16686:16686"
      - "6831:6831/udp"
  scws:
    depends_on:
      - jaeger
    image: scws:check
    environment:
      JAEGER_AGENT_HOST: "jaeger"
      JAEGER_AGENT_PORT: 6831
      # JAEGER_SAMPLING_ENDPOINT: http://jaeger:5778/sampling
      JAEGER_TAGS: "service=frontend"
      JAEGER_SERVICE_NAME: "scws"
      #JAEGER_REPORTER_LOG_SPANS: true
      SCWS_INDEXHTML: "calculator/index.html"
      SCWS_S3_BUCKET: ""
      SCWS_S3_PREFIX: "/"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_REGION: "eu-west-1"
      SCWS_STORAGE: "filesystem"
    ports:
      - "8080:8080"
  # parent:
  #   depends_on:
  #     - jaeger
  #     - scws
  #   image: parent:check
  #   environment:
  #     JAEGER_AGENT_HOST: "jaeger"
  #     JAEGER_AGENT_PORT: 6831
  #     JAEGER_TAGS: "service=parent"
  #     JAEGER_SERVICE_NAME: "parent"
  #     JAEGER_REPORTER_LOG_SPANS: true
