name: UnitTests

on:
  pull_request:
    paths:
      - '*.go'
      - '**/*.go'
    branches-ignore:
    - master

env:
  SCWS_STORAGE: "filesystem"
  JAEGER_DISABLED: true
  SCWS_SETTINGS_VAR_VAR1: "123"
  AWS_ACCESS_KEY_ID: "test"
  AWS_SECRET_ACCESS_KEY: "test"
  # SCWS_FS_ROOT: "/www/"

jobs:

  testing:
    name: UnitTests
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16.2
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Create www and index.html
      run: mkdir www && echo 1 > www/index.html

    - name: Get dependencies
      run: go mod download

    - name: UnitTests
      run: SCWS_FS_ROOT=`pwd`/www/ go test -v ./... -coverprofile=coverage.txt -covermode=atomic
